//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: query_language.proto
namespace RethinkDb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TableRef")]
  public partial class TableRef : global::ProtoBuf.IExtensible
  {
    public TableRef() {}
    
    private string _db_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"db_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string db_name
    {
      get { return _db_name; }
      set { _db_name = value; }
    }
    private string _table_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"table_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string table_name
    {
      get { return _table_name; }
      set { _table_name = value; }
    }

    private bool _use_outdated = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"use_outdated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool use_outdated
    {
      get { return _use_outdated; }
      set { _use_outdated = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VarTermTuple")]
  public partial class VarTermTuple : global::ProtoBuf.IExtensible
  {
    public VarTermTuple() {}
    
    private string _var;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"var", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string var
    {
      get { return _var; }
      set { _var = value; }
    }
    private Term _term;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"term", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term term
    {
      get { return _term; }
      set { _term = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Term")]
  public partial class Term : global::ProtoBuf.IExtensible
  {
    public Term() {}
    
    private Term.TermType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Term.TermType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private string _var = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"var", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string var
    {
      get { return _var; }
      set { _var = value; }
    }

    private Term.Let _let = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"let", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Term.Let let
    {
      get { return _let; }
      set { _let = value; }
    }

    private Term.Call _call = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"call", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Term.Call call
    {
      get { return _call; }
      set { _call = value; }
    }

    private Term.If _if_ = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"if_", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Term.If if_
    {
      get { return _if_; }
      set { _if_ = value; }
    }

    private string _error = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string error
    {
      get { return _error; }
      set { _error = value; }
    }

    private double _number = default(double);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double number
    {
      get { return _number; }
      set { _number = value; }
    }

    private string _valuestring = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"valuestring", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string valuestring
    {
      get { return _valuestring; }
      set { _valuestring = value; }
    }

    private string _jsonstring = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"jsonstring", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jsonstring
    {
      get { return _jsonstring; }
      set { _jsonstring = value; }
    }

    private bool _valuebool = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"valuebool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool valuebool
    {
      get { return _valuebool; }
      set { _valuebool = value; }
    }
    private readonly global::System.Collections.Generic.List<Term> _array = new global::System.Collections.Generic.List<Term>();
    [global::ProtoBuf.ProtoMember(11, Name=@"array", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Term> array
    {
      get { return _array; }
    }
  
    private readonly global::System.Collections.Generic.List<VarTermTuple> _object = new global::System.Collections.Generic.List<VarTermTuple>();
    [global::ProtoBuf.ProtoMember(12, Name=@"object", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<VarTermTuple> @object
    {
      get { return _object; }
    }
  

    private Term.GetByKey _get_by_key = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"get_by_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Term.GetByKey get_by_key
    {
      get { return _get_by_key; }
      set { _get_by_key = value; }
    }

    private Term.Table _table = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"table", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Term.Table table
    {
      get { return _table; }
      set { _table = value; }
    }

    private string _javascript = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"javascript", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string javascript
    {
      get { return _javascript; }
      set { _javascript = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Let")]
  public partial class Let : global::ProtoBuf.IExtensible
  {
    public Let() {}
    
    private readonly global::System.Collections.Generic.List<VarTermTuple> _binds = new global::System.Collections.Generic.List<VarTermTuple>();
    [global::ProtoBuf.ProtoMember(1, Name=@"binds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<VarTermTuple> binds
    {
      get { return _binds; }
    }
  
    private Term _expr;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"expr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term expr
    {
      get { return _expr; }
      set { _expr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Call")]
  public partial class Call : global::ProtoBuf.IExtensible
  {
    public Call() {}
    
    private Builtin _builtin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"builtin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Builtin builtin
    {
      get { return _builtin; }
      set { _builtin = value; }
    }
    private readonly global::System.Collections.Generic.List<Term> _args = new global::System.Collections.Generic.List<Term>();
    [global::ProtoBuf.ProtoMember(2, Name=@"args", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Term> args
    {
      get { return _args; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"If")]
  public partial class If : global::ProtoBuf.IExtensible
  {
    public If() {}
    
    private Term _test;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"test", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term test
    {
      get { return _test; }
      set { _test = value; }
    }
    private Term _true_branch;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"true_branch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term true_branch
    {
      get { return _true_branch; }
      set { _true_branch = value; }
    }
    private Term _false_branch;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"false_branch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term false_branch
    {
      get { return _false_branch; }
      set { _false_branch = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetByKey")]
  public partial class GetByKey : global::ProtoBuf.IExtensible
  {
    public GetByKey() {}
    
    private TableRef _table_ref;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"table_ref", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TableRef table_ref
    {
      get { return _table_ref; }
      set { _table_ref = value; }
    }
    private string _attrname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"attrname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string attrname
    {
      get { return _attrname; }
      set { _attrname = value; }
    }
    private Term _key;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term key
    {
      get { return _key; }
      set { _key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Table")]
  public partial class Table : global::ProtoBuf.IExtensible
  {
    public Table() {}
    
    private TableRef _table_ref;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"table_ref", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TableRef table_ref
    {
      get { return _table_ref; }
      set { _table_ref = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TermType")]
    public enum TermType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"JSON_NULL", Value=0)]
      JSON_NULL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VAR", Value=1)]
      VAR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LET", Value=2)]
      LET = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CALL", Value=3)]
      CALL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IF", Value=4)]
      IF = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR", Value=5)]
      ERROR = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NUMBER", Value=6)]
      NUMBER = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRING", Value=7)]
      STRING = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JSON", Value=8)]
      JSON = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOOL", Value=9)]
      BOOL = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARRAY", Value=10)]
      ARRAY = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBJECT", Value=11)]
      OBJECT = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GETBYKEY", Value=12)]
      GETBYKEY = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TABLE", Value=13)]
      TABLE = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JAVASCRIPT", Value=14)]
      JAVASCRIPT = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IMPLICIT_VAR", Value=15)]
      IMPLICIT_VAR = 15
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Builtin")]
  public partial class Builtin : global::ProtoBuf.IExtensible
  {
    public Builtin() {}
    
    private Builtin.BuiltinType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Builtin.BuiltinType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private string _attr = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string attr
    {
      get { return _attr; }
      set { _attr = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _attrs = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"attrs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> attrs
    {
      get { return _attrs; }
    }
  

    private Builtin.Comparison _comparison = Builtin.Comparison.EQ;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"comparison", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Builtin.Comparison.EQ)]
    public Builtin.Comparison comparison
    {
      get { return _comparison; }
      set { _comparison = value; }
    }

    private Builtin.Filter _filter = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"filter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Builtin.Filter filter
    {
      get { return _filter; }
      set { _filter = value; }
    }

    private Builtin.Map _map = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"map", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Builtin.Map map
    {
      get { return _map; }
      set { _map = value; }
    }

    private Builtin.ConcatMap _concat_map = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"concat_map", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Builtin.ConcatMap concat_map
    {
      get { return _concat_map; }
      set { _concat_map = value; }
    }
    private readonly global::System.Collections.Generic.List<Builtin.OrderBy> _order_by = new global::System.Collections.Generic.List<Builtin.OrderBy>();
    [global::ProtoBuf.ProtoMember(8, Name=@"order_by", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Builtin.OrderBy> order_by
    {
      get { return _order_by; }
    }
  

    private Reduction _reduce = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"reduce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Reduction reduce
    {
      get { return _reduce; }
      set { _reduce = value; }
    }

    private Builtin.GroupedMapReduce _grouped_map_reduce = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"grouped_map_reduce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Builtin.GroupedMapReduce grouped_map_reduce
    {
      get { return _grouped_map_reduce; }
      set { _grouped_map_reduce = value; }
    }

    private Builtin.Range _range = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"range", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Builtin.Range range
    {
      get { return _range; }
      set { _range = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Filter")]
  public partial class Filter : global::ProtoBuf.IExtensible
  {
    public Filter() {}
    
    private Predicate _predicate;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"predicate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Predicate predicate
    {
      get { return _predicate; }
      set { _predicate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Map")]
  public partial class Map : global::ProtoBuf.IExtensible
  {
    public Map() {}
    
    private Mapping _mapping;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapping", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Mapping mapping
    {
      get { return _mapping; }
      set { _mapping = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConcatMap")]
  public partial class ConcatMap : global::ProtoBuf.IExtensible
  {
    public ConcatMap() {}
    
    private Mapping _mapping;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapping", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Mapping mapping
    {
      get { return _mapping; }
      set { _mapping = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderBy")]
  public partial class OrderBy : global::ProtoBuf.IExtensible
  {
    public OrderBy() {}
    
    private string _attr;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string attr
    {
      get { return _attr; }
      set { _attr = value; }
    }

    private bool _ascending = (bool)true;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ascending", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool ascending
    {
      get { return _ascending; }
      set { _ascending = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GroupedMapReduce")]
  public partial class GroupedMapReduce : global::ProtoBuf.IExtensible
  {
    public GroupedMapReduce() {}
    
    private Mapping _group_mapping;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"group_mapping", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Mapping group_mapping
    {
      get { return _group_mapping; }
      set { _group_mapping = value; }
    }
    private Mapping _value_mapping;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value_mapping", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Mapping value_mapping
    {
      get { return _value_mapping; }
      set { _value_mapping = value; }
    }
    private Reduction _reduction;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"reduction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Reduction reduction
    {
      get { return _reduction; }
      set { _reduction = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Range")]
  public partial class Range : global::ProtoBuf.IExtensible
  {
    public Range() {}
    
    private string _attrname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"attrname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string attrname
    {
      get { return _attrname; }
      set { _attrname = value; }
    }

    private Term _lowerbound = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lowerbound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Term lowerbound
    {
      get { return _lowerbound; }
      set { _lowerbound = value; }
    }

    private Term _upperbound = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"upperbound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Term upperbound
    {
      get { return _upperbound; }
      set { _upperbound = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"BuiltinType")]
    public enum BuiltinType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT", Value=1)]
      NOT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GETATTR", Value=2)]
      GETATTR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IMPLICIT_GETATTR", Value=3)]
      IMPLICIT_GETATTR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HASATTR", Value=4)]
      HASATTR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IMPLICIT_HASATTR", Value=5)]
      IMPLICIT_HASATTR = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PICKATTRS", Value=6)]
      PICKATTRS = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IMPLICIT_PICKATTRS", Value=7)]
      IMPLICIT_PICKATTRS = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAPMERGE", Value=8)]
      MAPMERGE = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARRAYAPPEND", Value=9)]
      ARRAYAPPEND = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SLICE", Value=11)]
      SLICE = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADD", Value=14)]
      ADD = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUBTRACT", Value=15)]
      SUBTRACT = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MULTIPLY", Value=16)]
      MULTIPLY = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIVIDE", Value=17)]
      DIVIDE = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODULO", Value=18)]
      MODULO = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMPARE", Value=19)]
      COMPARE = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FILTER", Value=20)]
      FILTER = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAP", Value=21)]
      MAP = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONCATMAP", Value=22)]
      CONCATMAP = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDERBY", Value=23)]
      ORDERBY = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DISTINCT", Value=24)]
      DISTINCT = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LENGTH", Value=26)]
      LENGTH = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNION", Value=27)]
      UNION = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NTH", Value=28)]
      NTH = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STREAMTOARRAY", Value=29)]
      STREAMTOARRAY = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARRAYTOSTREAM", Value=30)]
      ARRAYTOSTREAM = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REDUCE", Value=31)]
      REDUCE = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPEDMAPREDUCE", Value=32)]
      GROUPEDMAPREDUCE = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ANY", Value=35)]
      ANY = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL", Value=36)]
      ALL = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANGE", Value=37)]
      RANGE = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IMPLICIT_WITHOUT", Value=38)]
      IMPLICIT_WITHOUT = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WITHOUT", Value=39)]
      WITHOUT = 39
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Comparison")]
    public enum Comparison
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQ", Value=1)]
      EQ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NE", Value=2)]
      NE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LT", Value=3)]
      LT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LE", Value=4)]
      LE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT", Value=5)]
      GT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GE", Value=6)]
      GE = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Reduction")]
  public partial class Reduction : global::ProtoBuf.IExtensible
  {
    public Reduction() {}
    
    private Term _base;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"base", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term @base
    {
      get { return _base; }
      set { _base = value; }
    }
    private string _var1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"var1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string var1
    {
      get { return _var1; }
      set { _var1 = value; }
    }
    private string _var2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"var2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string var2
    {
      get { return _var2; }
      set { _var2 = value; }
    }
    private Term _body;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"body", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term body
    {
      get { return _body; }
      set { _body = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mapping")]
  public partial class Mapping : global::ProtoBuf.IExtensible
  {
    public Mapping() {}
    
    private string _arg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"arg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string arg
    {
      get { return _arg; }
      set { _arg = value; }
    }
    private Term _body;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"body", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term body
    {
      get { return _body; }
      set { _body = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Predicate")]
  public partial class Predicate : global::ProtoBuf.IExtensible
  {
    public Predicate() {}
    
    private string _arg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"arg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string arg
    {
      get { return _arg; }
      set { _arg = value; }
    }
    private Term _body;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"body", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term body
    {
      get { return _body; }
      set { _body = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadQuery")]
  public partial class ReadQuery : global::ProtoBuf.IExtensible
  {
    public ReadQuery() {}
    
    private Term _term;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"term", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term term
    {
      get { return _term; }
      set { _term = value; }
    }

    private long _max_chunk_size = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"max_chunk_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long max_chunk_size
    {
      get { return _max_chunk_size; }
      set { _max_chunk_size = value; }
    }

    private long _max_age = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"max_age", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long max_age
    {
      get { return _max_age; }
      set { _max_age = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WriteQuery")]
  public partial class WriteQuery : global::ProtoBuf.IExtensible
  {
    public WriteQuery() {}
    
    private WriteQuery.WriteQueryType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public WriteQuery.WriteQueryType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private bool _atomic = (bool)true;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"atomic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool atomic
    {
      get { return _atomic; }
      set { _atomic = value; }
    }

    private WriteQuery.Update _update = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"update", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WriteQuery.Update update
    {
      get { return _update; }
      set { _update = value; }
    }

    private WriteQuery.Delete _delete = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"delete", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WriteQuery.Delete delete
    {
      get { return _delete; }
      set { _delete = value; }
    }

    private WriteQuery.Mutate _mutate = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mutate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WriteQuery.Mutate mutate
    {
      get { return _mutate; }
      set { _mutate = value; }
    }

    private WriteQuery.Insert _insert = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"insert", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WriteQuery.Insert insert
    {
      get { return _insert; }
      set { _insert = value; }
    }

    private WriteQuery.ForEach _for_each = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"for_each", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WriteQuery.ForEach for_each
    {
      get { return _for_each; }
      set { _for_each = value; }
    }

    private WriteQuery.PointUpdate _point_update = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"point_update", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WriteQuery.PointUpdate point_update
    {
      get { return _point_update; }
      set { _point_update = value; }
    }

    private WriteQuery.PointDelete _point_delete = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"point_delete", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WriteQuery.PointDelete point_delete
    {
      get { return _point_delete; }
      set { _point_delete = value; }
    }

    private WriteQuery.PointMutate _point_mutate = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"point_mutate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WriteQuery.PointMutate point_mutate
    {
      get { return _point_mutate; }
      set { _point_mutate = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Update")]
  public partial class Update : global::ProtoBuf.IExtensible
  {
    public Update() {}
    
    private Term _view;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"view", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term view
    {
      get { return _view; }
      set { _view = value; }
    }
    private Mapping _mapping;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapping", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Mapping mapping
    {
      get { return _mapping; }
      set { _mapping = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Delete")]
  public partial class Delete : global::ProtoBuf.IExtensible
  {
    public Delete() {}
    
    private Term _view;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"view", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term view
    {
      get { return _view; }
      set { _view = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mutate")]
  public partial class Mutate : global::ProtoBuf.IExtensible
  {
    public Mutate() {}
    
    private Term _view;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"view", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term view
    {
      get { return _view; }
      set { _view = value; }
    }
    private Mapping _mapping;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapping", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Mapping mapping
    {
      get { return _mapping; }
      set { _mapping = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Insert")]
  public partial class Insert : global::ProtoBuf.IExtensible
  {
    public Insert() {}
    
    private TableRef _table_ref;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"table_ref", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TableRef table_ref
    {
      get { return _table_ref; }
      set { _table_ref = value; }
    }
    private readonly global::System.Collections.Generic.List<Term> _terms = new global::System.Collections.Generic.List<Term>();
    [global::ProtoBuf.ProtoMember(2, Name=@"terms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Term> terms
    {
      get { return _terms; }
    }
  

    private bool _overwrite = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"overwrite", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool overwrite
    {
      get { return _overwrite; }
      set { _overwrite = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ForEach")]
  public partial class ForEach : global::ProtoBuf.IExtensible
  {
    public ForEach() {}
    
    private Term _stream;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stream", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term stream
    {
      get { return _stream; }
      set { _stream = value; }
    }
    private string _var;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"var", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string var
    {
      get { return _var; }
      set { _var = value; }
    }
    private readonly global::System.Collections.Generic.List<WriteQuery> _queries = new global::System.Collections.Generic.List<WriteQuery>();
    [global::ProtoBuf.ProtoMember(3, Name=@"queries", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<WriteQuery> queries
    {
      get { return _queries; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PointUpdate")]
  public partial class PointUpdate : global::ProtoBuf.IExtensible
  {
    public PointUpdate() {}
    
    private TableRef _table_ref;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"table_ref", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TableRef table_ref
    {
      get { return _table_ref; }
      set { _table_ref = value; }
    }
    private string _attrname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"attrname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string attrname
    {
      get { return _attrname; }
      set { _attrname = value; }
    }
    private Term _key;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term key
    {
      get { return _key; }
      set { _key = value; }
    }
    private Mapping _mapping;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"mapping", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Mapping mapping
    {
      get { return _mapping; }
      set { _mapping = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PointDelete")]
  public partial class PointDelete : global::ProtoBuf.IExtensible
  {
    public PointDelete() {}
    
    private TableRef _table_ref;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"table_ref", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TableRef table_ref
    {
      get { return _table_ref; }
      set { _table_ref = value; }
    }
    private string _attrname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"attrname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string attrname
    {
      get { return _attrname; }
      set { _attrname = value; }
    }
    private Term _key;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term key
    {
      get { return _key; }
      set { _key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PointMutate")]
  public partial class PointMutate : global::ProtoBuf.IExtensible
  {
    public PointMutate() {}
    
    private TableRef _table_ref;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"table_ref", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TableRef table_ref
    {
      get { return _table_ref; }
      set { _table_ref = value; }
    }
    private string _attrname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"attrname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string attrname
    {
      get { return _attrname; }
      set { _attrname = value; }
    }
    private Term _key;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term key
    {
      get { return _key; }
      set { _key = value; }
    }
    private Mapping _mapping;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"mapping", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Mapping mapping
    {
      get { return _mapping; }
      set { _mapping = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"WriteQueryType")]
    public enum WriteQueryType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE", Value=1)]
      UPDATE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETE", Value=2)]
      DELETE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MUTATE", Value=3)]
      MUTATE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INSERT", Value=4)]
      INSERT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOREACH", Value=6)]
      FOREACH = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"POINTUPDATE", Value=7)]
      POINTUPDATE = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"POINTDELETE", Value=8)]
      POINTDELETE = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"POINTMUTATE", Value=9)]
      POINTMUTATE = 9
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MetaQuery")]
  public partial class MetaQuery : global::ProtoBuf.IExtensible
  {
    public MetaQuery() {}
    
    private MetaQuery.MetaQueryType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MetaQuery.MetaQueryType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private string _db_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"db_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string db_name
    {
      get { return _db_name; }
      set { _db_name = value; }
    }

    private MetaQuery.CreateTable _create_table = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"create_table", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MetaQuery.CreateTable create_table
    {
      get { return _create_table; }
      set { _create_table = value; }
    }

    private TableRef _drop_table = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"drop_table", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TableRef drop_table
    {
      get { return _drop_table; }
      set { _drop_table = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateTable")]
  public partial class CreateTable : global::ProtoBuf.IExtensible
  {
    public CreateTable() {}
    

    private string _datacenter = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"datacenter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string datacenter
    {
      get { return _datacenter; }
      set { _datacenter = value; }
    }
    private TableRef _table_ref;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"table_ref", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TableRef table_ref
    {
      get { return _table_ref; }
      set { _table_ref = value; }
    }

    private string _primary_key = @"id";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"primary_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"id")]
    public string primary_key
    {
      get { return _primary_key; }
      set { _primary_key = value; }
    }

    private long _cache_size = (long)1073741824;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cache_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)1073741824)]
    public long cache_size
    {
      get { return _cache_size; }
      set { _cache_size = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MetaQueryType")]
    public enum MetaQueryType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_DB", Value=1)]
      CREATE_DB = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DROP_DB", Value=2)]
      DROP_DB = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LIST_DBS", Value=3)]
      LIST_DBS = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_TABLE", Value=4)]
      CREATE_TABLE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DROP_TABLE", Value=5)]
      DROP_TABLE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LIST_TABLES", Value=6)]
      LIST_TABLES = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Query")]
  public partial class Query : global::ProtoBuf.IExtensible
  {
    public Query() {}
    
    private Query.QueryType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Query.QueryType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private long _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long token
    {
      get { return _token; }
      set { _token = value; }
    }

    private ReadQuery _read_query = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"read_query", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ReadQuery read_query
    {
      get { return _read_query; }
      set { _read_query = value; }
    }

    private WriteQuery _write_query = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"write_query", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WriteQuery write_query
    {
      get { return _write_query; }
      set { _write_query = value; }
    }

    private MetaQuery _meta_query = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"meta_query", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MetaQuery meta_query
    {
      get { return _meta_query; }
      set { _meta_query = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"QueryType")]
    public enum QueryType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"READ", Value=1)]
      READ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WRITE", Value=2)]
      WRITE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONTINUE", Value=3)]
      CONTINUE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STOP", Value=4)]
      STOP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"META", Value=5)]
      META = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private Response.StatusCode _status_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Response.StatusCode status_code
    {
      get { return _status_code; }
      set { _status_code = value; }
    }
    private long _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long token
    {
      get { return _token; }
      set { _token = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _response = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> response
    {
      get { return _response; }
    }
  

    private string _error_message = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"error_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string error_message
    {
      get { return _error_message; }
      set { _error_message = value; }
    }

    private Response.Backtrace _backtrace = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"backtrace", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Response.Backtrace backtrace
    {
      get { return _backtrace; }
      set { _backtrace = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Backtrace")]
  public partial class Backtrace : global::ProtoBuf.IExtensible
  {
    public Backtrace() {}
    
    private readonly global::System.Collections.Generic.List<string> _frame = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"frame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> frame
    {
      get { return _frame; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"StatusCode")]
    public enum StatusCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS_EMPTY", Value=0)]
      SUCCESS_EMPTY = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS_JSON", Value=1)]
      SUCCESS_JSON = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS_PARTIAL", Value=2)]
      SUCCESS_PARTIAL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS_STREAM", Value=3)]
      SUCCESS_STREAM = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BROKEN_CLIENT", Value=101)]
      BROKEN_CLIENT = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BAD_QUERY", Value=102)]
      BAD_QUERY = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RUNTIME_ERROR", Value=103)]
      RUNTIME_ERROR = 103
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}