//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: rethinkdb_spec.proto
namespace RethinkDb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Query")]
  public partial class Query : global::ProtoBuf.IExtensible
  {
    public Query() {}
    
    private Query.QueryType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Query.QueryType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private Term _query = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"query", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Term query
    {
      get { return _query; }
      set { _query = value; }
    }
    private ulong _token;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong token
    {
      get { return _token; }
      set { _token = value; }
    }

    private bool _noreply = (bool)false;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"noreply", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool noreply
    {
      get { return _noreply; }
      set { _noreply = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"QueryType")]
    public enum QueryType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"START", Value=1)]
      START = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONTINUE", Value=2)]
      CONTINUE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STOP", Value=3)]
      STOP = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private Response.ResponseType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Response.ResponseType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private ulong _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong token
    {
      get { return _token; }
      set { _token = value; }
    }
    private readonly global::System.Collections.Generic.List<Datum> _response = new global::System.Collections.Generic.List<Datum>();
    [global::ProtoBuf.ProtoMember(3, Name=@"response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Datum> response
    {
      get { return _response; }
    }
  
    private readonly global::System.Collections.Generic.List<Response.Frame> _backtrace = new global::System.Collections.Generic.List<Response.Frame>();
    [global::ProtoBuf.ProtoMember(4, Name=@"backtrace", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Response.Frame> backtrace
    {
      get { return _backtrace; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Frame")]
  public partial class Frame : global::ProtoBuf.IExtensible
  {
    public Frame() {}
    
    private Response.Frame.FrameType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Response.Frame.FrameType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private ulong _pos = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong pos
    {
      get { return _pos; }
      set { _pos = value; }
    }

    private string _opt = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"opt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string opt
    {
      get { return _opt; }
      set { _opt = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"FrameType")]
    public enum FrameType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"POS", Value=1)]
      POS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPT", Value=2)]
      OPT = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResponseType")]
    public enum ResponseType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS_ATOM", Value=1)]
      SUCCESS_ATOM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS_SEQUENCE", Value=2)]
      SUCCESS_SEQUENCE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS_PARTIAL", Value=3)]
      SUCCESS_PARTIAL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_ERROR", Value=16)]
      CLIENT_ERROR = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMPILE_ERROR", Value=17)]
      COMPILE_ERROR = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RUNTIME_ERROR", Value=18)]
      RUNTIME_ERROR = 18
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Datum")]
  public partial class Datum : global::ProtoBuf.IExtensible
  {
    public Datum() {}
    
    private Datum.DatumType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Datum.DatumType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private bool _r_bool = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"r_bool", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool r_bool
    {
      get { return _r_bool; }
      set { _r_bool = value; }
    }

    private double _r_num = default(double);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"r_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double r_num
    {
      get { return _r_num; }
      set { _r_num = value; }
    }

    private string _r_str = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"r_str", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string r_str
    {
      get { return _r_str; }
      set { _r_str = value; }
    }
    private readonly global::System.Collections.Generic.List<Datum> _r_array = new global::System.Collections.Generic.List<Datum>();
    [global::ProtoBuf.ProtoMember(5, Name=@"r_array", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Datum> r_array
    {
      get { return _r_array; }
    }
  
    private readonly global::System.Collections.Generic.List<Datum.AssocPair> _r_object = new global::System.Collections.Generic.List<Datum.AssocPair>();
    [global::ProtoBuf.ProtoMember(6, Name=@"r_object", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Datum.AssocPair> r_object
    {
      get { return _r_object; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AssocPair")]
  public partial class AssocPair : global::ProtoBuf.IExtensible
  {
    public AssocPair() {}
    
    private string _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private Datum _val;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Datum val
    {
      get { return _val; }
      set { _val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"DatumType")]
    public enum DatumType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"R_NULL", Value=1)]
      R_NULL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"R_BOOL", Value=2)]
      R_BOOL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"R_NUM", Value=3)]
      R_NUM = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"R_STR", Value=4)]
      R_STR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"R_ARRAY", Value=5)]
      R_ARRAY = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"R_OBJECT", Value=6)]
      R_OBJECT = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Term")]
  public partial class Term : global::ProtoBuf.IExtensible
  {
    public Term() {}
    
    private Term.TermType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Term.TermType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private Datum _datum = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"datum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Datum datum
    {
      get { return _datum; }
      set { _datum = value; }
    }
    private readonly global::System.Collections.Generic.List<Term> _args = new global::System.Collections.Generic.List<Term>();
    [global::ProtoBuf.ProtoMember(3, Name=@"args", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Term> args
    {
      get { return _args; }
    }
  
    private readonly global::System.Collections.Generic.List<Term.AssocPair> _optargs = new global::System.Collections.Generic.List<Term.AssocPair>();
    [global::ProtoBuf.ProtoMember(4, Name=@"optargs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Term.AssocPair> optargs
    {
      get { return _optargs; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AssocPair")]
  public partial class AssocPair : global::ProtoBuf.IExtensible
  {
    public AssocPair() {}
    
    private string _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private Term _val;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Term val
    {
      get { return _val; }
      set { _val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TermType")]
    public enum TermType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DATUM", Value=1)]
      DATUM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAKE_ARRAY", Value=2)]
      MAKE_ARRAY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAKE_OBJ", Value=3)]
      MAKE_OBJ = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VAR", Value=10)]
      VAR = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JAVASCRIPT", Value=11)]
      JAVASCRIPT = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR", Value=12)]
      ERROR = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IMPLICIT_VAR", Value=13)]
      IMPLICIT_VAR = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB", Value=14)]
      DB = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TABLE", Value=15)]
      TABLE = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET", Value=16)]
      GET = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQ", Value=17)]
      EQ = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NE", Value=18)]
      NE = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LT", Value=19)]
      LT = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LE", Value=20)]
      LE = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT", Value=21)]
      GT = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GE", Value=22)]
      GE = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT", Value=23)]
      NOT = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADD", Value=24)]
      ADD = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUB", Value=25)]
      SUB = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MUL", Value=26)]
      MUL = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIV", Value=27)]
      DIV = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOD", Value=28)]
      MOD = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"APPEND", Value=29)]
      APPEND = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SLICE", Value=30)]
      SLICE = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GETATTR", Value=31)]
      GETATTR = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONTAINS", Value=32)]
      CONTAINS = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLUCK", Value=33)]
      PLUCK = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WITHOUT", Value=34)]
      WITHOUT = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MERGE", Value=35)]
      MERGE = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BETWEEN", Value=36)]
      BETWEEN = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REDUCE", Value=37)]
      REDUCE = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAP", Value=38)]
      MAP = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FILTER", Value=39)]
      FILTER = 39,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONCATMAP", Value=40)]
      CONCATMAP = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDERBY", Value=41)]
      ORDERBY = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DISTINCT", Value=42)]
      DISTINCT = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COUNT", Value=43)]
      COUNT = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNION", Value=44)]
      UNION = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NTH", Value=45)]
      NTH = 45,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPED_MAP_REDUCE", Value=46)]
      GROUPED_MAP_REDUCE = 46,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPBY", Value=47)]
      GROUPBY = 47,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INNER_JOIN", Value=48)]
      INNER_JOIN = 48,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OUTER_JOIN", Value=49)]
      OUTER_JOIN = 49,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQ_JOIN", Value=50)]
      EQ_JOIN = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COERCE", Value=51)]
      COERCE = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TYPEOF", Value=52)]
      TYPEOF = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE", Value=53)]
      UPDATE = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETE", Value=54)]
      DELETE = 54,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REPLACE", Value=55)]
      REPLACE = 55,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INSERT", Value=56)]
      INSERT = 56,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_CREATE", Value=57)]
      DB_CREATE = 57,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_DROP", Value=58)]
      DB_DROP = 58,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_LIST", Value=59)]
      DB_LIST = 59,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TABLE_CREATE", Value=60)]
      TABLE_CREATE = 60,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TABLE_DROP", Value=61)]
      TABLE_DROP = 61,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TABLE_LIST", Value=62)]
      TABLE_LIST = 62,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUNCALL", Value=64)]
      FUNCALL = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BRANCH", Value=65)]
      BRANCH = 65,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ANY", Value=66)]
      ANY = 66,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL", Value=67)]
      ALL = 67,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOREACH", Value=68)]
      FOREACH = 68,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUNC", Value=69)]
      FUNC = 69
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Version")]
    public enum Version
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"V0_1", Value=1063369270)]
      V0_1 = 1063369270
    }
  
}